experiment_name: p7-ray-batch-inference-v2
mlflow_run_name: ray-batch-v2-staged
environment:
  version: 'databricks_ai_v5'
  dependencies:
    - ray[data]
compute:
  num_accelerators: 1
  accelerator_type: GPU_1xA10
code_source:
  type: snapshot
  snapshot:
    root_path: .
command: |
  python $CODE_SOURCE_PATH/ray_batch_inference_v2.py
